name: FluxGithubApp
options:
  deploymentTarget:
    iOS: 13.0
  bundleIdPrefix: takashico.FluxGithubApp

settings:
  base:
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: G4J97F9LZ2

packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    version: 7.3.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    version: 6.5.0
  PKHUD:
    url: https://github.com/pkluz/PKHUD
    version: 5.4.0
  Swinject:
    url: https://github.com/Swinject/Swinject
    version: 2.8.1
  SwinjectStoryboard:
    url: https://github.com/Swinject/SwinjectStoryboard
    version: 2.2.2

targets:
  FluxGithubApp:
    type: application
    platform: iOS
    sources:
      - FluxGithubApp
    dependency:
      - package: RxCocoa
      - package: RxRelay
      - package: RxSwift
      - package: Swinject
      - package: SwinjectStoryboard
      - package: Kingfisher
      - package: PKHUD

  FluxGithubAppTests:
    type: bundle.unit-test
    sources:
      - FluxGithubAppTests

  FluxGithubAppUITests:
    type: bundle.ui-testing
    sources:
      - FluxGithubAppUITests